[package]
authors = ["jrconlin <jconlin+git@mozilla.com>"]
name = "pushbox"
version = "0.1.0"
[dependencies]
failure = "0.1.1"
futures = "0.1.21"
mysql = "13.1.0"
rand = "0.5.0"
reqwest = "0.8.6"
rocket = "0.3.12"
rocket_codegen = "0.3.12"
rusoto_core = "0.32.0"
rusoto_sqs = "0.32.0"
serde = "1.0.64"
serde_derive = "1.0.64"
serde_json = "1.0.19"
slog = "2.2.3"
slog-async = "2.3.0"
slog-json = "2.2.0"
slog-scope = "4.0.1"
slog-stdlog = "3.0.2"
slog-term = "2.4.0"
time = "0.1.40"

[dependencies.diesel]
features = ["mysql", "r2d2"]
version = "~1.2"

[dependencies.diesel_migrations]
features = ["mysql"]
version = "~1.2"

[dependencies.rocket_contrib]
default-features = true
version = "0.3.12"
