service: pushbox

frameworkVersion: "=1.26.1"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.6
  memorySize: 128
  environment:
    S3_BUCKET:
      Ref: dataBucket
    DDB_TABLE:
      Ref: indexTable
    FXA_SERVER_KEY: ${env:FXA_SERVER_KEY}

plugins:
  - serverless-python-requirements
  - serverless-offline
#  - serverless-domain-manager
package:
  exclude:
    - .gitignore
    - .idea/**
    - .git/**
    - lib/.git/**
    - local/lib/python2.7/**
    - local/node_modules/**
    - .serverless
    - node_modules/**
    - scripts/**
    - local/include/**

functions:
  store_data:
    handler: handler.store_data
    role: storeDataRole
    events:
      - http:
          authorizer:
            name: fxaAuthorizer
            identitySource: method.request.header.Authorization
            type: token
          path: v1/store/{uid}/{deviceId}
          method: post
          cors: true
  get_data:
    handler: handler.get_data
    role: getDataRole
    events:
      - http:
          authorizer:
            name: fxaAuthorizer
            identitySource: method.request.header.Authorization
            type: token
          path: v1/store/{uid}/{deviceId}
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                index: false
                max_size: false
                count: false
  del_user_device_data:
    handler: handler.del_data
    role: storeDataRole
    events:
      - http:
          authorizer:
            name: fxaAuthorizer
            identitySource: method.request.header.Authorization
            type: token
          path: v1/store/{uid}/{deviceId}
          method: delete
          cors: true
  health:
    handler: handler.status
    role: getDataRole
    events:
      - http:
          path: v1/status
          method: get
          cors: true
  fxaAuthorizer:
    handler: fxa_auth.fxa_validate

resources:
  Resources:
    # Our base serverless policy
    serverlessPolicy:
      Type: AWS::IAM::Policy
      Properties:
        Roles:
          - Ref: storeDataRole
          - Ref: getDataRole
        PolicyName: serverlessPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - 'Fn::Join':
                  - ':'
                  -
                    - 'arn:aws:logs'
                    - Ref: 'AWS::Region'
                    - Ref: 'AWS::AccountId'
                    - 'log-group:/aws/lambda/*:*:*'
            - Effect: "Allow"
              Action:
                 - "s3:PutObject"
              Resource:
                 Fn::Join:
                   - ""
                   - - "arn:aws:s3:::"
                     - "Ref" : "ServerlessDeploymentBucket"
# Required for domain-manager
#            - Effect: Allow
#              Action:
#                - apigateway:POST
#              Resource: "/domainnames"
#            - Effect: Allow
#              Action:
#                - apigateway:GET
#                - apigateway:DELETE
#              Resource: "/domainnames/*"
#            - Effect: Allow
#              Action:
#                - apigateway:POST
#              Resource: "/domainnames/*/basepathmappings"
#            - Effect: Allow
#              Action:
#                - route53:ListHostedZones
#              Resource: "*"
#            - Effect: Allow
#              Action:
#                - acm:ListCertificates
#              Resource: "*"
#            - Effect: Allow
#              Action:
#                - cloudfront:UpdateDistribution
#              Resource: "*"
#            - Effect: Allow
#              Action:
#                - route53:ChangeResourceRecordSets
#                - route53:GetHostedZone
#                - route53:ListResourceRecordSets
#              Resource: "arn:aws:route53::hostedzone/Z3GEB01DYXZM0A"

    indexTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: indexTable_${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: fxa_uid
            AttributeType: S
          - AttributeName: index
            AttributeType: N
        KeySchema:
          - AttributeName: fxa_uid
            KeyType: HASH
          - AttributeName: index
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    dataBucket:
      Type: AWS::S3::Bucket

    storeDataRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: storeDataPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                    - "s3:PutObjectAcl"
                    - "s3:DeleteObject"
                  Resource:
                    - Fn::Join: ['', ['arn:aws:s3:::', Ref: "dataBucket", "/*"]]
                - Effect: "Allow"
                  Action:
                    - "dynamodb:GetItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Query"
                  Resource:
                    Fn::GetAtt:
                      - indexTable
                      - Arn

    getDataRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: getDataPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Allow"
                  Action:
                    - "s3:GetObject"
                  Resource:
                    - Fn::Join: ['', ['arn:aws:s3:::', Ref: "dataBucket", "/*"]]
                - Effect: "Allow"
                  Action:
                    - "dynamodb:GetItem"
                    - "dynamodb:Query"
                  Resource:
                    Fn::GetAtt:
                      - indexTable
                      - Arn
# Required for domain-manager
#custom:
#  customDomain:
#      domainName: "pushbox.dev.mozaws.net"
#      # See note in DEPLOY.md about possible bug here.
#      certificateName: "*.dev.mozaws.net"
#      basePath: ""
#      stage: ${self:provider.stage}
#      createRoute53Record: true
